repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.5
    hooks:
      # Run the linter.
      - id: ruff
        args:
        - "--fix"
        - "--show-fixes"
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: uv run pytest
      exclude: ^examples/
      language: system
      types: [python]
